# Demo 01 - Primer GitHub Action
# Workflow básico para el primer contacto

name: Demo 01 - Básico

# Cuándo se ejecuta
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  primer-contacto:
    name: "Mi Primer Workflow"
    runs-on: ubuntu-latest
    
    steps:
    # 1. Obtener el código
    - name: Obtener código
      uses: actions/checkout@v4 #git clone
    
    # 2. Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    # 3. Información del sistema
    - name: Mostrar información del sistema
      run: |
        echo "GitHub Actions está funcionando correctamente"
        echo "Ejecutado por: ${{ github.actor }}"
        echo "En la rama: ${{ github.ref }}"
        echo "Fecha: $(date)"
        echo "Sistema: ${{ runner.os }}"
    
    # 4. Verificar que Node.js funciona
    - name: Verificar Node.js
      run: |
        echo "Versión de Node: $(node --version)"
        echo "Versión de NPM: $(npm --version)"
        echo "Node.js está funcionando correctamente"
    
    # 5. Instalar dependencias
    - name: Instalar dependencias
      run: |
        echo "Instalando dependencias..."
        npm install
        echo "Dependencias instaladas correctamente"
    
    # 6. Verificar estructura del proyecto
    - name: Verificar proyecto
      run: |
        echo "Estructura del proyecto:"
        ls -la
        echo ""
        echo "Verificaciones:"
        echo "package.json: $(test -f package.json && echo 'Existe' || echo 'No existe')"
        echo "src/: $(test -d src && echo 'Existe' || echo 'No existe')"
        echo "tests/: $(test -d tests && echo 'Existe' || echo 'No existe')"
    
    # 7. Mensaje final
    - name: Resumen
      run: |
        echo "Workflow completado exitosamente"
        echo "GitHub Actions puede automatizar cualquier tarea"
        echo "Siguiente paso: Ejecutar tests automáticamente"